---
name: "Media Retention Guardian"
guid: "5c5422c9-396b-4dec-87fa-a8a20f65c549"
version: "0.1.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Automatise la purge des fichiers après la durée de conservation définie."
description: >
  Supprime automatiquement les fichiers d'un ou plusieurs dossiers lorsque la durée de
  conservation configurée est dépassée, avec suivi des suppressions et planification quotidienne.
category: "Maintenance"
owner: "seb"
artifacts:
  - "MediaRetentionGuardian.dll"
  - "logo.svg"
  - "thumb.png"
changelog: |-
  - Initial multi-dossier retention support.
